"use client";
import {useEffect,useState} from 'react';
import {browserClient} from '@/lib/supabase-browser';
export default function Login(){
 const [email,setEmail]=useState(''),[error,setError]=useState(''),[user,setUser]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{browserClient().auth.getUser().then(({data})=>setUser(data.user?.email??'')).catch(()=>setError('กรุณาตั้งค่า Supabase ก่อนใช้งาน'));},[]);
 async function login(){setError('');if(!/^[^@\s]+@gmail\.com$/i.test(email))return setError('ใช้อีเมลเฉพาะ Gmail เท่านั้น');setBusy(true);try{sessionStorage.setItem('expected-email',email.toLowerCase().trim());const {error}=await browserClient().auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/auth/callback',queryParams:{login_hint:email,prompt:'select_account'}}});if(error)throw error;}catch(e){setError(e instanceof Error?e.message:'เข้าสู่ระบบไม่สำเร็จ');setBusy(false);}}
 return <div className="email-page"><header className="masthead"><a className="brand" href="/"><div className="brand-mark"><img src="/logos/smg.png" alt="SMG"/></div><strong>SMG MANUFACTURING CLUB</strong></a></header><main className="email-main"><a href="/">กลับ Dashboard</a><section className="email-panel"><h1>ยืนยันอีเมลผู้รายงาน</h1><p className="gmail-only-notice">ใช้อีเมลเฉพาะ Gmail เท่านั้น</p><p>ยืนยันตัวตนผ่าน Google ผู้ดูแลต้องอนุญาตอีเมลสำหรับบริษัทก่อนส่งรายงาน</p>{user?<><p>เข้าสู่ระบบ: {user}</p><a className="btn primary" href="/">ไปส่งรายงาน</a><button className="btn secondary" onClick={async()=>{await browserClient().auth.signOut();setUser('');}}>ออกจากระบบ / เปลี่ยนบัญชี</button></>:<form className="email-form" onSubmit={e=>{e.preventDefault();void login();}}><label htmlFor="email">อีเมล</label><input id="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="yourname@gmail.com"/><button disabled={busy} className="btn primary">{busy?'กำลังเข้าสู่ระบบ…':'เข้าสู่ระบบด้วย Google'}</button></form>}{error&&<p className="email-error" role="alert">{error}</p>}</section></main></div>;
}
