const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');const Module=require('node:module');
const root=path.resolve(__dirname,'..');let user=null,allowed=false,objects=[],rpcCalls=0,previous=null;
const query=()=>{const q={select(){return q},eq(){return q},gte(){return q},lt(){return q},not(){return q},is(){return q},in(){return q},order(){return q},limit(){return q},range(){return Promise.resolve({data:[],error:null})},maybeSingle(){return Promise.resolve({data:previous,error:null})},then(resolve,reject){return Promise.resolve({data:objects,error:null,count:0}).then(resolve,reject)}};return q;};
let lastReport=null;
const mock={reportUser:async()=>user,canReport:async()=>allowed,reportAuthor:(u,company)=>u.userId==='public'?`public:${company}`:u.userId,sameOrigin:req=>!req.headers.get('origin')||req.headers.get('origin')===new URL(req.url).origin,adminClient:()=>({from:()=>query(),rpc:async(_name,args)=>{rpcCalls++;lastReport=args.p_report;return {error:null}},storage:{from:()=>({download:async()=>({data:new Blob([new Uint8Array([255,216,255,0])]),error:null})})}})};
function load(file){const m=new Module(file);m.filename=file;m.paths=module.paths;m.require=id=>{if(id==='@/lib/supabase-server')return mock;if(id==='server-only')return {};if(id==='@supabase/supabase-js')return {createClient:()=>{throw Error('Public mode should not call Supabase Auth')}};if(id.startsWith('@/'))return load(path.join(root,id.slice(2)+'.ts'));if(id.startsWith('.'))return load(path.resolve(path.dirname(file),id+'.ts'));return require(id)};m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,file);return m.exports;}
const api=load(path.join(root,'app/api/reports/route.ts'));
const {today}=load(path.join(root,'lib/flood.ts'));
function request(fields={}){const f=new FormData();for(const [k,v] of Object.entries({company:'BKC',date:today(),time:'00:00',point:'ทางเข้าหลัก',level:'115',status:'normal',road:'ผ่านได้',attendance:'มาทำงานได้ปกติ',production:'ไม่กระทบต่อกระบวนการผลิต',transport:'ไม่มีผลกระทบ',photoUploads:JSON.stringify([{id:'11111111-1111-4111-8111-111111111111',point:'exterior'},{id:'22222222-2222-4222-8222-222222222222',point:'entrance'}]),...fields}))f.set(k,v);return new Request('https://example.com/api/reports',{method:'POST',body:f});}
test('report authorization, validation and server risk calculation',async()=>{
 user=null;allowed=false;assert.equal((await api.POST(request())).status,401);
 user={userId:'user-id',email:'reporter@gmail.com',displayName:'Reporter'};assert.equal((await api.POST(request())).status,403);
 allowed=true;assert.equal((await api.POST(request({date:'2999-01-01'}))).status,400);
 assert.equal((await api.POST(request({attendance:'ยังไม่ทราบ'}))).status,400);
 assert.equal((await api.POST(request({photoUploads:'[]'}))).status,400);
 assert.equal((await api.POST(request())).status,400);assert.equal(rpcCalls,0);
 objects=[{id:'11111111-1111-4111-8111-111111111111',point:'exterior',path:'a'},{id:'22222222-2222-4222-8222-222222222222',point:'entrance',path:'b'}];
 const good=await api.POST(request());assert.equal(good.status,201);assert.equal((await good.json()).status,'critical');assert.equal(rpcCalls,1);
 const badOrigin=request();badOrigin.headers.set('origin','https://attacker.example');assert.equal((await api.POST(badOrigin)).status,403);
});
test('pagination rejects invalid page and exposes normalized empty response',async()=>{assert.equal((await api.GET(new Request('https://example.com/api/reports?page=-1'))).status,400);const res=await api.GET(new Request('https://example.com/api/reports?page=0'));assert.equal(res.status,200);assert.deepEqual((await res.json()).reports,[]);});
test('public report records a shared author without an account',async()=>{user={userId:'public',email:'',displayName:'ผู้ส่งรายงานทั่วไป'};allowed=true;const res=await api.POST(request());assert.equal(res.status,201);assert.equal(lastReport.author,'public:BKC');assert.equal(lastReport.reporter,'ผู้ส่งรายงานทั่วไป');assert.equal(lastReport.production,'ไม่กระทบต่อกระบวนการผลิต');});
test('public mode accepts browser requests without Google login',async()=>{const old=process.env.NEXT_PUBLIC_REPORT_AUTH_MODE;process.env.NEXT_PUBLIC_REPORT_AUTH_MODE='public';try{const auth=load(path.join(root,'lib/supabase-server.ts'));const anon=await auth.reportUser(new Request('https://example.com/api/reports'));assert.equal(anon.userId,'public');assert.equal(await auth.canReport('', 'BKC'),true);assert.equal(auth.reportAuthor(anon,'BKC'),'public:BKC');}finally{if(old===undefined)delete process.env.NEXT_PUBLIC_REPORT_AUTH_MODE;else process.env.NEXT_PUBLIC_REPORT_AUTH_MODE=old;}});
