"use client";
import {authFetch,fetchReports,uploadPhoto} from '@/lib/supabase-browser';
import PrintReport from './print-report';
import LanguageToggle from '@/components/language-toggle';
import {photoPointLabels,photoPointLabel,validatePhotoCounts,PhotoPoint} from '@/lib/report-photos';
import {companyLogos} from '@/lib/company-logos';
import {readApiResponse} from '@/lib/api-client';
import {useState,useEffect,useMemo} from 'react';
import {Waves,LayoutDashboard,ClipboardList,History,Plus,RefreshCw,Building2,CheckCircle2,Clock,TriangleAlert,ShieldCheck,Search,Camera,MapPin,Truck,Factory,ChevronRight,ArrowUp,ArrowDown,Minus,ImagePlus,Eye,CloudRain,Printer,FileCheck2,Loader2,LogIn,CalendarDays,UserRound} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import {ResponsiveContainer,AreaChart,Area,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {companies,statuses,Report,Status,today,dateLabel,timeLabel,latestFor,trendFor,situationPriority,productionLabel,transportLabel,attendanceLabel,waterLevels,waterLevelFor,waterLevelLabel} from '@/lib/flood';

const publicMode=process.env.NEXT_PUBLIC_REPORT_AUTH_MODE==='public';
const alphabeticalCompanies=[...companies].sort(([codeA],[codeB])=>codeA.localeCompare(codeB,'en'));
function Pick({value,onChange,options,label,placeholder}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string;placeholder?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
function CalendarDateField({id,value,onChange,max,label}:{id?:string;value:string;onChange:(v:string)=>void;max?:string;label:string}){return <span className="calendar-field"><CalendarDays size={18}/><span className="calendar-date-text" aria-hidden="true">{dateLabel(value)}</span><input id={id} required type="date" value={value} max={max} aria-label={label} onChange={e=>e.target.value&&onChange(e.target.value)} onClick={e=>e.currentTarget.showPicker?.()}/></span>;}
function WaterLevelPicker({value,onChange}:{value:string;onChange:(value:string)=>void}){return <fieldset className="water-level-field full"><legend>ระดับน้ำ</legend><div className="water-level-options">{waterLevels.map((item,index)=><label key={item.value} className={`water-level-option ${item.tone} ${value===item.value?'selected':''}`}><input type="radio" name="waterLevel" value={item.value} checked={value===item.value} onChange={()=>onChange(item.value)}/><span className="water-level-visual"><UserRound size={30}/><i style={{height:`${8+index*12}%`}}/></span><b>{item.label}</b><small>{item.range}</small></label>)}</div></fieldset>;}
function CompanyLogo({code,name}:{code:string;name:string}){const [failed,setFailed]=useState(false);const logo=companyLogos[code];return <div className={`company-logo-box logo-${code.toLowerCase()}`}>{logo&&!failed?<img src={logo.src} alt={`โลโก้ ${name}`} loading="lazy" onError={()=>setFailed(true)}/>:<span>{code}</span>}</div>;}
function Badge({status}:{status:Status}){const s=statuses[status];return <span className={`badge ${status}`}>{status==='critical'?<TriangleAlert size={14} aria-hidden="true"/>:<span/>}{s.label}</span>;}
function Trend({rows,report}:{rows:Report[];report:Report|undefined}){const t=trendFor(rows,report);if(!t)return <span className="trend quiet">ยังเปรียบเทียบไม่ได้</span>;return <span className={`trend ${t.diff>0?'up':t.diff<0?'down':'quiet'}`} title={`เทียบกับ ${dateLabel(t.date)} ณ จุดวัดเดียวกัน`}>{t.diff>0?<ArrowUp size={14}/>:t.diff<0?<ArrowDown size={14}/>:<Minus size={14}/>} {t.diff===0?'คงที่':`${t.diff>0?'เพิ่ม':'ลด'} ${Math.abs(t.diff)} ซม.`}</span>;}
function Photo({report,compact=false}:{report:Report|undefined;compact?:boolean}){return report?.photos.length?<div className={`report-photo-grid ${compact?'compact':''}`}>{report.photos.map((id,i)=><figure key={id}><a href={`/api/photos/${id}`} target="_blank" rel="noopener noreferrer" aria-label={`เปิดภาพ ${i+1} ${photoPointLabel(report.photoPoints?.[i])} ของ ${report.company}`}><img src={`/api/photos/${id}`} alt={`${report.company} · ${photoPointLabel(report.photoPoints?.[i])} · ภาพที่ ${i+1}`} loading="lazy" style={{ width: '100%', height: '160px', objectFit: 'cover', borderRadius: '6px' }}/></a><figcaption>{photoPointLabel(report.photoPoints?.[i])}</figcaption></figure>)}</div>:<div className={compact?'photo-empty small':'photo-empty'}><Camera size={compact?22:28}/><span>{report?'ยังไม่มีภาพหลักฐาน':'รอภาพจากบริษัท'}</span>{!compact&&<small>ภาพหน้าบริษัทประจำวัน</small>}</div>;}
function UploadPoint({point,files,onChange}:{point:PhotoPoint;files:File[];onChange:(files:File[])=>void}){
 const [urls,setUrls]=useState<string[]>([]);useEffect(()=>{const next=files.map(f=>URL.createObjectURL(f));setUrls(next);return()=>next.forEach(u=>URL.revokeObjectURL(u));},[files]);
 return <div className="upload-point full"><label className="upload-area"><ImagePlus size={25}/><b>{point==='exterior'?'1.':'2.'} {photoPointLabels[point]}</b><span>ต้องแนบจุดละ 1–3 ภาพ • JPEG, PNG, WebP • ไม่เกินภาพละ 5 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{onChange(Array.from(e.target.files??[]));e.currentTarget.value='';}} aria-label={`แนบรูป ${photoPointLabels[point]}`}/></label>{files.length>0&&<div className="upload-previews">{urls.map((url,i)=><div key={url}><img src={url} alt={`${photoPointLabels[point]} ภาพที่ ${i+1}`}/><button type="button" onClick={()=>onChange(files.filter((_,j)=>j!==i))} aria-label={`ลบภาพที่ ${i+1} ${photoPointLabels[point]}`}>×</button><small>{files[i]?.name}</small></div>)}</div>}</div>;
}
function Chart({rows,code,date}:{rows:Report[];code:string;date:string}){
 const points=useMemo(()=>{const end=new Date(date+'T00:00:00Z');return Array.from({length:7},(_,i)=>{const d=new Date(end);d.setUTCDate(d.getUTCDate()-(6-i));const key=d.toISOString().slice(0,10);const r=latestFor(rows,code,key);return {date:key,label:d.toLocaleDateString('th-TH',{day:'numeric',month:'short'}),level:r?.level??null};});},[rows,code,date]);
 if(!points.some(p=>p.level!==null))return <div className="chart-empty"><Waves/><p>ยังไม่มีข้อมูลระดับน้ำในช่วงนี้</p></div>;
 return <div className="chart" role="img" aria-label={`ระดับน้ำของ ${code} ย้อนหลัง 7 วัน`}><ResponsiveContainer width="100%" height={205}><AreaChart data={points} margin={{top:12,right:12,left:-22,bottom:0}}><defs><linearGradient id={`water-${code}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#1689bc" stopOpacity={0.3}/><stop offset="100%" stopColor="#1689bc" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e6edf3"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#718097'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#718097'}} unit=""/><Tooltip formatter={(v)=>[`${v} ซม.`,'ระดับน้ำ']} contentStyle={{borderRadius:10,border:'1px solid #dbe4ee',fontSize:14}}/><Area type="linear" dataKey="level" stroke="#1689bc" strokeWidth={3} fill={`url(#water-${code})`} connectNulls={false} dot={{r:3,fill:'#1689bc',strokeWidth:2,stroke:'#fff'}}/></AreaChart></ResponsiveContainer><small className="quiet">หน่วย: เซนติเมตร • ใช้รายงานล่าสุดของแต่ละวัน</small></div>;
}

const companyColors=['#1268ad','#198b67','#d66b22','#8b5abd','#c33960','#0097a7','#947722','#3853a4','#b34231','#6b8056','#835467','#267c95','#b87917','#5477bf','#a15199','#3a897b','#7a5738','#505f80','#ba4949'];
function AllCompanyChart({rows,date,compact=false}:{rows:Report[];date:string;compact?:boolean}){
 const [selected,setSelected]=useState<string[]>(companies.map(([code])=>code));
 const selectedCompanies=companies.filter(([code])=>selected.includes(code));
 function toggle(code:string){setSelected(current=>current.includes(code)?current.filter(c=>c!==code):[...current,code]);}

 const points=useMemo(()=>{const end=new Date(date+'T00:00:00Z');return Array.from({length:7},(_,i)=>{const d=new Date(end);d.setUTCDate(d.getUTCDate()-(6-i));const key=d.toISOString().slice(0,10);return {date:key,label:d.toLocaleDateString('th-TH',{day:'numeric',month:'short'}),...Object.fromEntries(companies.map(([code])=>[code,latestFor(rows,code,key)?.level??null]))};});},[rows,date]);
 const hasData=points.some(p=>selectedCompanies.some(([code])=>(p as unknown as Record<string,unknown>)[code]!==null));
 return <div className="all-company-trends"><details className="compare-picker"><summary>เลือกบริษัทเปรียบเทียบ <b>{selected.length} / {companies.length}</b></summary><div className="compare-options"><div className="compare-actions"><button type="button" onClick={()=>setSelected(companies.map(([c])=>c))}>เลือกทั้งหมด</button><button type="button" onClick={()=>setSelected([])}>ล้างการเลือก</button></div>{companies.map(([code,name])=><label key={code}><input type="checkbox" checked={selected.includes(code)} onChange={()=>toggle(code)}/><b>{code}</b><span>{name}</span></label>)}</div></details><div className="company-legend" aria-label="สีประจำบริษัท">{selectedCompanies.map(([code,name],i)=><span key={code} title={name}><i style={{background:companyColors[companies.findIndex(([c])=>c===code)]}}/>{code}</span>)}</div>{hasData?<div className="all-company-chart" role="img" aria-label={`กราฟเปรียบเทียบระดับน้ำย้อนหลัง 7 วัน ${selected.join(", ")}`}><ResponsiveContainer width="100%" height={compact?210:300}><LineChart data={points} margin={{top:12,right:18,left:-14,bottom:8}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e6edf3"/><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#718097'}}/><YAxis tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#718097'}}/><Tooltip filterNull formatter={(v,name)=>[`${v} ซม.`,name]} contentStyle={{borderRadius:9,border:'1px solid #dbe4ee',fontSize:13,maxHeight:320,overflowY:'auto'}}/>{selectedCompanies.map(([code],i)=><Line key={code} type="linear" dataKey={code} name={code} stroke={companyColors[companies.findIndex(([c])=>c===code)]} strokeWidth={2} strokeDasharray={companies.findIndex(([c])=>c===code)>=10?'6 3':undefined} connectNulls={false} dot={{r:3,strokeWidth:1,fill:companyColors[companies.findIndex(([c])=>c===code)]}} activeDot={{r:5}} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div>:<div className="chart-empty"><Waves/><p>{selected.length?'ยังไม่มีข้อมูลระดับน้ำของบริษัทที่เลือกในช่วงนี้':'เลือกบริษัทเพื่อเปรียบเทียบระดับน้ำ'}</p></div>}<p className="trend-caption">หน่วย: เซนติเมตร • รายงานล่าสุดของแต่ละวัน • วันที่ไม่มีข้อมูลจะเว้นช่องว่างในกราฟ</p>{!compact&&<div className="all-trends-table"><Table><TableHeader><TableRow><TableHead>บริษัท / วันที่</TableHead>{points.map(p=><TableHead key={p.date}>{p.label}</TableHead>)}</TableRow></TableHeader><TableBody>{selectedCompanies.map(([code,name],i)=><TableRow key={code}><TableCell title={name}><b className="legend-table-code"><i style={{background:companyColors[companies.findIndex(([c])=>c===code)]}}/>{code}</b></TableCell>{points.map(p=>{const value=(p as unknown as Record<string,unknown>)[code];return <TableCell key={p.date} className={value===null?'no-level':''}>{value===null?'—':String(value)}</TableCell>;})}</TableRow>)}</TableBody></Table></div>}<p className="trend-caption">— = ไม่มีรายงานระดับน้ำหรือยังไม่ได้วัด • 0 = รายงานว่าไม่มีน้ำ</p></div>;
}

export default function Dashboard({signInHref,initialAuthenticated}:{signInHref:string;initialAuthenticated:boolean}){
 const [authenticated,setAuthenticated]=useState(initialAuthenticated);
 const [real,setReal]=useState<Report[]>([]),[date,setDate]=useState(today()),[filter,setFilter]=useState('all'),[companyFilter,setCompanyFilter]=useState('all'),[tab,setTab]=useState('summary'),[detail,setDetail]=useState<string|null>(null),[form,setForm]=useState(false),[chartCompany,setChartCompany]=useState('GYSI'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 const [currentDay,setCurrentDay]=useState(today()),[lastChecked,setLastChecked]=useState<string|null>(null),[detailDate,setDetailDate]=useState(today());
 const [reportCompany,setReportCompany]=useState<string|null>(null);
 const rows=real;const totalCompanies=companies.length;
 function openDetail(code:string,d:string=date){setDetailDate(d);setDetail(code);}
 async function refresh(){setLoading(true);setError('');try{const data=await fetchReports();if(!Array.isArray(data.reports))throw Error('ข้อมูลรายงานไม่ถูกต้อง กรุณาลองใหม่');setReal(data.reports as Report[]);setAuthenticated(data.authenticated===true);setLoaded(true);setCurrentDay(today());setLastChecked(new Date().toISOString());}catch(e){setError(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ');}finally{setLoading(false);}}
 useEffect(()=>{void refresh();const t=setInterval(()=>{void refresh();},60000);const wake=()=>{if(document.visibilityState==='visible')void refresh();};document.addEventListener('visibilitychange',wake);window.addEventListener('focus',wake);return()=>{clearInterval(t);document.removeEventListener('visibilitychange',wake);window.removeEventListener('focus',wake);};},[]);
 const records=companies.map(([code,name])=>({code,name,r:latestFor(rows,code,date)}));const count=(s:Status)=>records.filter(x=>(x.r?.status??'missing')===s).length;const reported=records.filter(x=>x.r).length;
 const visible=records.filter(x=>(filter==='all'||(filter==='reported'?!!x.r:(x.r?.status??'missing')===filter))&&(companyFilter==='all'||x.code===companyFilter)).sort((a,b)=>situationPriority(b.r?.status??'missing')-situationPriority(a.r?.status??'missing'));
 const summaryVisible=records.filter(x=>(filter==='all'||(filter==='reported'?!!x.r:(x.r?.status??'missing')===filter))&&(companyFilter==='all'||x.code===companyFilter)).sort((a,b)=>situationPriority(b.r?.status??'missing')-situationPriority(a.r?.status??'missing'));
 
 const missing=records.filter(x=>!x.r);const detailRecord=companies.map(([code,name])=>({code,name,r:latestFor(rows,code,detailDate)})).find(x=>x.code===detail);
 const latest=records.filter(x=>x.r).map(x=>x.r!.submitted).sort().at(-1);
 async function printSummary(){if(!loaded||loading){toast.error('รอโหลดรายงานให้เสร็จก่อนพิมพ์');return;}if(error){toast.error('กรุณาโหลดข้อมูลให้สำเร็จก่อนพิมพ์');return;}const images=Array.from(document.querySelectorAll<HTMLImageElement>('.pdf-report img'));const result=await Promise.all(images.map(img=>Promise.race([img.decode().then(()=>true).catch(()=>false),new Promise<boolean>(resolve=>setTimeout(()=>resolve(false),15000))])));if(result.some(ok=>!ok)){toast.error('รูปบางภาพยังโหลดไม่สำเร็จ กรุณาตรวจสอบการเชื่อมต่อแล้วลองพิมพ์อีกครั้ง');return;}await document.fonts.ready;window.print();}
 return <div className={`app ${tab==='summary'?'summary-mode':''}`}><Toaster richColors position="top-center"/><header className="masthead"><div className="brand"><div className="brand-mark"><img src="/logos/smg.png" alt="โลโก้ SMG Manufacturing Club"/></div><div><strong>SMG MANUFACTURING CLUB</strong><span>FLOOD MONITORING</span></div></div><div className="header-right"><span className="club-tag">{totalCompanies} COMPANIES · ONE DASHBOARD</span>{publicMode?<span className="signed-in-label"><ShieldCheck size={16}/>เปิดรับรายงานทั่วไป</span>:authenticated?<span className="signed-in-label"><ShieldCheck size={16}/>เข้าสู่ระบบแล้ว <a href="/verify-email" style={{color:'inherit',marginLeft:8}}>บัญชี</a></span>:<a className="header-sign-in" href={signInHref} target="_top"><LogIn size={16}/>ยืนยันอีเมล / เข้าสู่ระบบ</a>}</div></header>
 <Tabs value={tab} onValueChange={setTab}><div className="nav-wrap"><TabsList className="nav-tabs" variant="line"><TabsTrigger value="summary"><LayoutDashboard/>ภาพรวมสถานการณ์</TabsTrigger><TabsTrigger value="reports"><ClipboardList/>สถานะรายงาน</TabsTrigger><TabsTrigger value="history"><History/>ข้อมูลย้อนหลัง</TabsTrigger></TabsList><div className="nav-tools"><LanguageToggle/><a className="cctv-nav-link" href="/cctv"><Camera size={17}/>CCTV ดอนหัวฬ่อ</a><span className="nav-meta"><Clock size={14}/> เวลาไทย (UTC+7)</span></div></div>
 <main><div className="page-title"><div><p className="eyebrow">DAILY FLOOD SITUATION</p><h1>{tab==='summary'?'ภาพรวมสถานการณ์น้ำท่วม · SMG MANUFACTURING CLUB':tab==='reports'?`รายงานประจำวัน ${totalCompanies} บริษัท · SMG MANUFACTURING CLUB`:'ติดตามระดับน้ำย้อนหลัง · SMG MANUFACTURING CLUB'}</h1><p className="subtitle">ติดตามสถานการณ์และผลกระทบต่อการดำเนินงานของ SMG Manufacturing Club</p></div><div className="title-actions"><button className="btn secondary" onClick={()=>void printSummary()}><Printer size={17}/>พิมพ์ / PDF</button><button className="btn primary report-action" onClick={()=>{setReportCompany(null);setForm(true);}}><Plus size={18}/>ส่งรายงานประจำวัน</button></div></div>
 <div className="mode-banner real"><div><Eye size={18}/><span><b>ข้อมูลรายงานจริง</b> • รายงานที่บันทึกผ่านแบบฟอร์มเท่านั้น</span></div></div>
 <div className="toolbar"><div className="toolbar-filters"><div className="date-control"><label htmlFor="report-date">วันที่รายงาน</label><CalendarDateField id="report-date" value={date} onChange={setDate} max={today()} label="กดเลือกวันที่รายงานจากปฏิทิน"/></div><div className="company-filter-control"><label>กรองบริษัท</label><Pick value={companyFilter} onChange={setCompanyFilter} label="กรองบริษัท" options={[{value:'all',label:'บริษัททั้งหมด (ไม่กรอง)'},...alphabeticalCompanies.map(([code,name])=>({value:code,label:`${code} — ${name}`}))]}/></div></div><div className="refresh"><span>{latest?`รายงานล่าสุด ${timeLabel(latest)} น.`:loaded?'ยังไม่มีรายงานในวันที่เลือก':'กำลังโหลดข้อมูล'}</span><button className="icon-btn" aria-label="รีเฟรชรายงาน" onClick={()=>void refresh()}><RefreshCw size={17} className={loading?'spin':''}/></button></div></div>
 {error&&<div className="error-bar" role="alert">{error}<button onClick={()=>void refresh()}>ลองอีกครั้ง</button></div>}
 {loading&&!loaded&&<div className="loading-state"><Loader2 className="spin"/>กำลังโหลดรายงานจริง…</div>}
 {(error&&!loaded)?<div className="empty">ยังไม่สามารถสรุปสถานะได้จนกว่าจะโหลดข้อมูลสำเร็จ</div>:<>
 <div className="stats"><button type="button" className={`stat total ${filter==='all'?'selected':''}`} onClick={()=>setFilter('all')} aria-pressed={filter==='all'} aria-label={`ดูบริษัททั้งหมด ${totalCompanies} บริษัท`}><div><span>บริษัททั้งหมด</span><Building2/></div><strong>{totalCompanies}<small>บริษัท</small></strong><p>สมาชิก SMG Manufacturing Club</p></button><button type="button" className={`stat reported ${filter==='reported'?'selected':''}`} onClick={()=>setFilter('reported')} aria-pressed={filter==='reported'} aria-label={`ดูบริษัทที่รายงานแล้ว ${reported} บริษัท`}><div><span>รายงานแล้ว</span><FileCheck2/></div><strong>{reported}<small>/ {totalCompanies}</small></strong><Progress value={reported/totalCompanies*100} className="report-progress"/><p>{Math.round(reported/totalCompanies*100)}% ของบริษัททั้งหมด</p></button>{(['normal','watch','warning','critical'] as Status[]).map(s=><button type="button" key={s} className={`stat ${s} ${filter===s?'selected':''}`} onClick={()=>setFilter(s)} aria-pressed={filter===s} aria-label={`ดูบริษัทสถานะ${statuses[s].label} ${count(s)} บริษัท`}><div><span>{statuses[s].label}</span>{s==='normal'?<ShieldCheck/>:<TriangleAlert/>}</div><strong>{count(s)}<small>บริษัท</small></strong><p>{s==='normal'?'รายงานสถานะปกติ':s==='watch'?'ควรติดตามใกล้ชิด':s==='warning'?'การดำเนินงานได้รับผลกระทบ':'ต้องติดตามเร่งด่วน'}</p></button>)}</div>
 {missing.length>0&&<div className="missing-banner"><Clock size={18}/><span><b>รอรายงาน {missing.length} บริษัท</b><span className="missing-codes">{missing.map(x=>x.code).join(' · ')}</span></span><button onClick={()=>{setTab('reports');setFilter('missing');}}>ตรวจสอบรายงาน<ChevronRight size={16}/></button></div>}
 <TabsContent value="summary">
  <section className="one-page-summary" aria-label="สรุปสถานการณ์ทุกบริษัท">
   {summaryVisible.length?<div className="summary-company-grid">{summaryVisible.map(({code,name,r})=><article key={code} className={`summary-company ${r?.status??'missing'}`} role="button" tabIndex={0} aria-label={`ดูรายละเอียด ${code} ${name}`} onClick={()=>openDetail(code)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDetail(code);}}}><div className="summary-company-head"><CompanyLogo code={code} name={name}/><span className="summary-company-code" title={name}>{code}</span><Badge status={r?.status??'missing'}/></div><div className="summary-images">{r?.photos.length?r.photos.map((id,i)=><a key={id} href={`/api/photos/${id}`} target="_blank" rel="noopener noreferrer" title={photoPointLabel(r.photoPoints?.[i])} onClick={e=>e.stopPropagation()}><img src={`/api/photos/${id}`} alt={`${code} ${photoPointLabel(r.photoPoints?.[i])}`} loading="lazy" style={{ width: '100%', height: '110px', objectFit: 'cover', borderRadius: '4px' }}/></a>):<div className="summary-no-photo"><Camera size={20}/><span>รอภาพรายงาน</span></div>}</div><div className="summary-water"><Waves size={15}/><strong className="water-band-label">{waterLevelFor(r?.level)?.label??'—'}</strong><span>{waterLevelFor(r?.level)?.range??(r?'ไม่ได้ระบุ':'ยังไม่รายงาน')}</span></div><div className="summary-facts"><span>Risk Score <b>{r?.riskScore==null?'—':`${r.riskScore}/10`}</b></span><span>ทางเข้า <b>{r?.road??'—'}</b></span><span>พนักงาน <b>{attendanceLabel(r?.attendance)}</b></span><span>การผลิต <b>{productionLabel(r?.production)}</b></span><span>การจัดส่ง <b>{transportLabel(r?.transport)}</b></span></div></article>)}</div>:<div className="summary-filter-empty"><ClipboardList/><b>ไม่มีบริษัทตามตัวกรองที่เลือก</b><button type="button" className="btn secondary" onClick={()=>{setFilter('all');setCompanyFilter('all');}}>ดูบริษัททั้งหมด</button></div>}
   {filter==='all'&&companyFilter==='all'&&<div className="summary-bottom summary-priority-only"><section className="panel summary-priority"><div className="panel-head"><h2>บริษัทที่ต้องติดตาม</h2></div>{records.filter(x=>x.r&&x.r.status!=='normal').length?records.filter(x=>x.r&&x.r.status!=='normal').sort((a,b)=>situationPriority(b.r?.status??'missing')-situationPriority(a.r?.status??'missing')).map(({code,r})=><button key={code} onClick={()=>openDetail(code)}><b>{code}</b><Badge status={r!.status}/><strong>{waterLevelFor(r!.level)?.label??'—'}</strong></button>):<p className="quiet">ยังไม่มีรายงานสถานะเฝ้าระวัง มีผลกระทบ หรือวิกฤตในวันที่เลือก</p>}<div className="summary-wait"><b>รอรายงาน {missing.length} บริษัท</b><p>{missing.map(x=>x.code).join(' · ')||'ส่งรายงานครบแล้ว'}</p></div><small className="quiet">ระดับน้ำแสดงตามช่วงความสูงที่บริษัทเลือก • — = ยังไม่มีข้อมูล</small></section></div>}
  </section>
 </TabsContent>
 <TabsContent value="reports"><div className="reports-layout">
  <section className="panel"><div className="panel-head"><div><h2>เปรียบเทียบแนวโน้มระดับน้ำ</h2><p>ย้อนหลัง 7 วัน ณ วันที่เลือก</p></div></div><AllCompanyChart rows={rows} date={date} compact/></section>
  <section className="panel"><div className="panel-head"><div><h2>สถานะการส่งรายงาน</h2><p>{dateLabel(date)} • สถานะคำนวณอัตโนมัติจาก Risk Score</p></div><Pick value={filter} onChange={setFilter} label="กรองสถานะในตาราง" options={[{value:'all',label:'ทุกสถานะ'},{value:'reported',label:'รายงานแล้ว'},...Object.entries(statuses).map(([value,s])=>({value,label:s.label}))]}/></div><Table><TableHeader><TableRow>{['บริษัท','สถานการณ์','Risk Score','ระดับน้ำ','ทางเข้า–ออก','การผลิต','สำรวจ / ส่ง','รายละเอียด'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(({code,name,r})=><TableRow key={code}><TableCell><b>{code}</b><span className="table-name">{name}</span></TableCell><TableCell><Badge status={r?.status??'missing'}/></TableCell><TableCell>{r?.riskScore==null?'—':`${r.riskScore}/10`}</TableCell><TableCell>{waterLevelLabel(r?.level)}</TableCell><TableCell>{r?.road??'—'}</TableCell><TableCell>{productionLabel(r?.production)}</TableCell><TableCell>{r?`${timeLabel(r.observed)} / ${timeLabel(r.submitted)}`:'—'}</TableCell><TableCell><button className="text-btn" onClick={()=>openDetail(code)}>ดูข้อมูล</button></TableCell></TableRow>)}</TableBody></Table></section>
 </div></TabsContent>
 <TabsContent value="history"><section className="panel history-panel"><div className="panel-head"><div><h2>ประวัติระดับน้ำและรายงาน</h2><p>เก็บทุกรอบที่ส่ง โดยไม่เขียนทับรายงานเดิม</p></div><Pick value={chartCompany} onChange={setChartCompany} label="บริษัทในประวัติ" options={alphabeticalCompanies.map(([c])=>({value:c,label:c}))}/></div><Chart rows={rows} code={chartCompany} date={date}/><ReportHistory rows={rows.filter(r=>r.company===chartCompany&&r.date<=date)}/></section></TabsContent>
 </>}
 <footer><span><Waves size={16}/>SMG MANUFACTURING CLUB · Flood Monitoring System</span><span>ข้อมูลจากรายงานของบริษัท · เขตเวลา Asia/Bangkok</span></footer>
 </main></Tabs>
 <Dialog open={detail!==null} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="detail-dialog"><DialogTitle>{detailRecord&&<CompanyLogo code={detailRecord.code} name={detailRecord.name}/>} {detailRecord?.code} <span className="quiet">· รายละเอียดบริษัท</span></DialogTitle><DialogDescription>{detailRecord?.name} · {dateLabel(detailDate)}</DialogDescription>{detailRecord&&<>{detailRecord.r?.status==='critical'&&<div className="critical-card-alert detail-critical"><TriangleAlert size={18}/>สถานะวิกฤต · ต้องติดตามเร่งด่วน</div>}<div className="detail-main"><Photo report={detailRecord.r}/><div className="detail-water"><Badge status={detailRecord.r?.status??'missing'}/><span>ระดับน้ำ ณ {detailRecord.r?.point??'จุดวัดหน้าบริษัท'}</span><strong className="detail-water-band">{waterLevelFor(detailRecord.r?.level)?.label??'—'}<small>{waterLevelFor(detailRecord.r?.level)?.range?` · ${waterLevelFor(detailRecord.r?.level)?.range}`:''}</small></strong><Trend rows={rows} report={detailRecord.r}/><span>{detailRecord.r?`สำรวจ ${timeLabel(detailRecord.r.observed)} น.`:'ยังไม่มีรายงานสำหรับวันที่เลือก'}</span></div></div>{detailRecord.r?<><div className="detail-facts">{[['ทางเข้า–ออก',detailRecord.r.road],['การมาทำงานของพนักงาน',attendanceLabel(detailRecord.r.attendance)],['การผลิต',productionLabel(detailRecord.r.production)],['การจัดส่ง (ผลกระทบลูกค้า)',transportLabel(detailRecord.r.transport)],['ผู้รายงาน',detailRecord.r.reporter]].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div><div className="note"><b>รายละเอียดสถานการณ์</b><p>{detailRecord.r.note||'ไม่มีรายละเอียดเพิ่มเติม'}</p>{detailRecord.r.help&&<p>ความช่วยเหลือที่ต้องการ: {detailRecord.r.help}</p>}</div><h3 className="detail-section">แนวโน้มระดับน้ำ 7 วัน</h3><Chart rows={rows} code={detailRecord.code} date={detailDate}/></>:<div className="empty"><ClipboardList/><p>บริษัทนี้ยังไม่ได้ส่งรายงานในวันที่เลือก</p><button className="btn primary" onClick={()=>{setReportCompany(detailRecord.code);setDetail(null);setForm(true);}}>ส่งรายงาน</button></div>}<ReportHistory rows={rows.filter(r=>r.company===detailRecord.code&&r.date<=detailDate).slice(0,10)}/></>}</DialogContent></Dialog>
 <ReportForm initialCompany={reportCompany} authenticated={authenticated} signInHref={signInHref} onAuthChecked={setAuthenticated} open={form} onOpenChange={setForm} onSaved={async(d:string)=>{setDate(d);setFilter('all');await refresh();toast.success('บันทึกรายงานและคำนวณ Risk Score เรียบร้อยแล้ว');}}/>
 <PrintReport rows={rows} date={date}/>
 </div>;
}
function ReportHistory({rows}:{rows:Report[]}){const sorted=[...rows].sort((a,b)=>b.observed.localeCompare(a.observed)||b.submitted.localeCompare(a.submitted));return <div className="history-list"><h3>ประวัติการรายงาน</h3>{sorted.length?sorted.slice(0,30).map(r=><div key={r.id} className="history-row"><div className="history-date"><b>{dateLabel(r.date)}</b><span>สำรวจ {timeLabel(r.observed)} · ส่ง {timeLabel(r.submitted)} น.</span></div><Badge status={r.status}/><strong className="history-water-band">{waterLevelFor(r.level)?.label??'—'} <small>{waterLevelFor(r.level)?.range??''}</small></strong>{r.photos.length>0&&<a className="text-btn" href={`/api/photos/${r.photos[0]}`} target="_blank" rel="noreferrer">ดูรูป</a>}</div>):<p className="empty-small">ยังไม่มีรายงานย้อนหลัง</p>}</div>;}

function ReportForm({open,onOpenChange,onSaved,authenticated,signInHref,onAuthChecked,initialCompany}:{open:boolean;onOpenChange:(v:boolean)=>void;onSaved:(date:string)=>Promise<void>;authenticated:boolean;signInHref:string;onAuthChecked:(v:boolean)=>void;initialCompany:string|null}){
 const now=()=>new Date().toLocaleTimeString('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit'});
 const [company,setCompany]=useState(''),[date,setDate]=useState(today()),[time,setTime]=useState(now()),[level,setLevel]=useState(''),[point,setPoint]=useState('Main Entrance'),[status,setStatus]=useState('normal'),[road,setRoad]=useState('ผ่านได้'),[attendance,setAttendance]=useState('มาทำงานได้ปกติ'),[production,setProduction]=useState('ไม่กระทบต่อกระบวนการผลิต'),[transport,setTransport]=useState('ไม่มีผลกระทบ'),[note,setNote]=useState(''),[help,setHelp]=useState(''),[exteriorFiles,setExteriorFiles]=useState<File[]>([]),[entranceFiles,setEntranceFiles]=useState<File[]>([]),[previews,setPreviews]=useState<string[]>([]),[review,setReview]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const fixedCompany=initialCompany?companies.find(([code])=>code===initialCompany):undefined;
 const files=useMemo(()=>[...exteriorFiles,...entranceFiles],[exteriorFiles,entranceFiles]);
 useEffect(()=>{if(open){setCompany(fixedCompany?.[0]??'');setDate(today());setTime(now());setReview(false);setError('');}},[open,initialCompany]);
 useEffect(()=>{const urls=files.map(f=>URL.createObjectURL(f));setPreviews(urls);return()=>urls.forEach(u=>URL.revokeObjectURL(u));},[files]);
 function validate(){
  setError('');
  if(!company||!date||!time||!point.trim()){
   setError('กรอกบริษัท วันที่ เวลา และจุดวัดให้ครบ');
   setTimeout(()=>document.getElementById(!company?'field-company':'field-point')?.scrollIntoView({behavior:'smooth',block:'center'}),50);
   return;
  }
  if(date>today()||Date.parse(`${date}T${time}:00+07:00`)>Date.now()+60000){
   setError('วันที่และเวลาสำรวจต้องไม่อยู่ในอนาคต');
   setTimeout(()=>document.getElementById('field-date')?.scrollIntoView({behavior:'smooth',block:'center'}),50);
   return;
  }
  if(!waterLevels.some(x=>x.value===level)){
   setError('กรุณาเลือกระดับน้ำจากรายการ');
   setTimeout(()=>document.getElementById('field-level')?.scrollIntoView({behavior:'smooth',block:'center'}),50);
   return;
  }
  if(!validatePhotoCounts(exteriorFiles.length,entranceFiles.length)||files.some(f=>f.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type))){
   setError('แนบภาพครบทั้ง 2 จุด จุดละ 1–3 ภาพ เป็น JPEG, PNG หรือ WebP ขนาดไม่เกินภาพละ 5 MB');
   setTimeout(()=>document.getElementById('field-photos')?.scrollIntoView({behavior:'smooth',block:'start'}),50);
   return;
  }
  setReview(true);
 }
 async function submit(){if(saving)return;setSaving(true);setError('');try{const sessionResponse=await authFetch('/api/reports',{headers:{Accept:'application/json'},credentials:'same-origin',redirect:'error',cache:'no-store'});const session=await readApiResponse<{authenticated:boolean}>(sessionResponse);onAuthChecked(session.authenticated===true);if(!session.authenticated)throw Error('กรุณากดปุ่มเข้าสู่ระบบด้วย Google จากนั้นกลับมาแท็บนี้แล้วกดยืนยันส่งรายงานอีกครั้ง ข้อมูลและรูปภาพที่เลือกยังอยู่ในแท็บนี้');const f=new FormData();Object.entries({company,date,time,level,point,status,road,attendance,production,transport,note,help}).forEach(([k,v])=>f.set(k,v));const uploads=[];for(const file of exteriorFiles)uploads.push(await uploadPhoto(file,'exterior',company));for(const file of entranceFiles)uploads.push(await uploadPhoto(file,'entrance',company));f.set('photoUploads',JSON.stringify(uploads));const res=await authFetch('/api/reports',{method:'POST',body:f,headers:{Accept:'application/json'},credentials:'same-origin',redirect:'error'});const data=await readApiResponse<{id:string}>(res);if(typeof data.id!=='string')throw Error('ระบบยังไม่ยืนยันการบันทึก กรุณาตรวจสอบรายงานก่อนส่งซ้ำ');onOpenChange(false);setReview(false);setExteriorFiles([]);setEntranceFiles([]);setLevel('');setNote('');setHelp('');await onSaved(date);}catch(e){setError(e instanceof TypeError?'การเชื่อมต่อขัดข้อง กรุณาตรวจสอบอินเทอร์เน็ตและสถานะเข้าสู่ระบบ แล้วลองส่งอีกครั้ง ข้อมูลในแบบฟอร์มยังอยู่':e instanceof Error?e.message:'บันทึกไม่สำเร็จ กรุณาลองอีกครั้ง');}finally{setSaving(false);}}
 const options=(values:string[])=>values.map(v=>({value:v,label:v}));
 return <Dialog open={open} onOpenChange={v=>{if(!saving){onOpenChange(v);if(!v)setReview(false);}}}><DialogContent className="report-dialog"><DialogTitle><ClipboardList size={22}/>{review?'ตรวจสอบก่อนส่งรายงาน':'รายงานสถานการณ์ประจำวัน'}</DialogTitle><DialogDescription>บันทึกข้อมูลจริงพร้อมภาพหลักฐาน • อัปเดตเพิ่มเติมได้โดยเก็บรายงานเดิมไว้</DialogDescription><div className="form-steps"><span className={!review?'active':''}>1 ข้อมูลและรูปภาพ</span><span className={review?'active':''}>2 ตรวจสอบและส่ง</span></div>
 {authenticated?<div className="report-auth ready"><ShieldCheck size={18}/><span>{publicMode?'ส่งรายงานได้โดยไม่ต้องเข้าสู่ระบบ':'เข้าสู่ระบบแล้ว · พร้อมส่งรายงาน'}</span></div>:<div className="report-auth"><LogIn size={20}/><div><b>เข้าสู่ระบบก่อนส่งรายงาน</b><p>ใช้บัญชี Google ของผู้รายงาน เมื่อเข้าสู่ระบบแล้วให้กลับมาแท็บนี้ ข้อมูลและรูปภาพจะยังอยู่</p><a className="btn primary" href={signInHref} target="_blank" rel="noopener noreferrer"><LogIn size={16}/>ยืนยันอีเมล / เข้าสู่ระบบ ↗</a></div></div>}
 {!review?<form onSubmit={e=>{e.preventDefault();validate();}}>
  <div className="form-grid">
   <h3 className="form-section-title full">1. ข้อมูลบริษัทและรายงาน</h3>
   <label className="full" id="field-company">บริษัท <b style={{color:'#e11d48',marginLeft:'4px'}}>*</b>{fixedCompany?<div className="fixed-company-value"><CompanyLogo code={fixedCompany[0]} name={fixedCompany[1]}/><b>{fixedCompany[0]}</b><span>{fixedCompany[1]}</span><small>บริษัทที่เลือกไว้</small></div>:<Pick value={company} onChange={setCompany} label="บริษัทผู้รายงาน" placeholder="เลือกบริษัทที่ต้องการส่งรายงาน" options={alphabeticalCompanies.map(([c,n])=>({value:c,label:`${c} — ${n}`}))}/>}</label>
   <label id="field-date">วันที่รายงาน <b style={{color:'#e11d48',marginLeft:'4px'}}>*</b><div className="readonly-report-field" aria-label={`วันที่รายงาน ${dateLabel(date)}`}><CalendarDays size={18}/><b>{dateLabel(date)}</b><small>อัตโนมัติ</small></div></label>
   <label>เวลาสำรวจ (เวลาไทย) <b style={{color:'#e11d48',marginLeft:'4px'}}>*</b><div className="readonly-report-field" aria-label={`เวลาสำรวจ ${time} นาฬิกา`}><Clock size={18}/><b>{time} น.</b><small>อัตโนมัติ</small></div></label>
   <label id="field-point">จุดวัดน้ำ <b style={{color:'#e11d48',marginLeft:'4px'}}>*</b><input required maxLength={100} value={point} onChange={e=>setPoint(e.target.value)} placeholder="เช่น ทางเข้าหลัก"/></label>
   
   <h3 className="form-section-title full">2. การประเมินสถานการณ์และผลกระทบต่อการดำเนินงาน</h3>
   <label>สถานการณ์ที่บริษัทประเมิน (ระบบคำนวณผลสุดท้าย) <b style={{color:'#e11d48',marginLeft:'4px'}}>*</b><Pick label="สถานการณ์บริษัท" value={status} onChange={setStatus} options={Object.entries(statuses).filter(([s])=>s!=='missing').map(([value,s])=>({value,label:s.label}))}/></label>
   <label>ทางเข้า–ออก <b style={{color:'#e11d48',marginLeft:'4px'}}>*</b><Pick label="สถานะทางเข้า" value={road} onChange={setRoad} options={options(['ผ่านได้','ผ่านได้บางประเภท','ผ่านไม่ได้'])}/></label>
   <label>การมาทำงานของพนักงาน <b style={{color:'#e11d48',marginLeft:'4px'}}>*</b><Pick label="การมาทำงานของพนักงาน" value={attendance} onChange={setAttendance} options={options(['มาทำงานได้ปกติ','มาทำงานได้แต่ต้องใช้แผนฉุกเฉิน (รถรับส่ง)','มาทำงานไม่ได้'])}/></label>
   <label>ผลกระทบต่อการผลิต <b style={{color:'#e11d48',marginLeft:'4px'}}>*</b><Pick label="ผลกระทบการผลิต" value={production} onChange={setProduction} options={options(['ไม่กระทบต่อกระบวนการผลิต','กระทบการผลิตบางส่วน','หยุดกระบวนการผลิต'])}/></label>
   <label>การจัดส่ง (ผลกระทบลูกค้า) <b style={{color:'#e11d48',marginLeft:'4px'}}>*</b><Pick label="การจัดส่ง ผลกระทบลูกค้า" value={transport} onChange={setTransport} options={options(['ไม่มีผลกระทบ','ล่าช้า','เข้า–ออกไม่ได้'])}/></label>
   
   <h3 className="form-section-title full">3. ระดับน้ำและรายละเอียดสถานการณ์</h3>
   <span id="field-level"><WaterLevelPicker value={level} onChange={setLevel}/></span>
   <label className="full">รายละเอียดสถานการณ์ / เส้นทาง<textarea rows={3} value={note} maxLength={2000} onChange={e=>setNote(e.target.value)} placeholder="ระบุจุดน้ำขัง ถนน และประเภทรถที่ตรวจสอบได้"/></label>
   <label className="full">ความช่วยเหลือที่ต้องการ<input value={help} maxLength={1000} onChange={e=>setHelp(e.target.value)} placeholder="ระบุหากต้องการความช่วยเหลือ"/></label>
   
   <h3 className="form-section-title full" id="field-photos">4. ภาพหลักฐาน <b style={{color:'#e11d48',marginLeft:'4px'}}>*</b></h3>
   <UploadPoint point="exterior" files={exteriorFiles} onChange={v=>{setExteriorFiles(v);setError('');}}/><UploadPoint point="entrance" files={entranceFiles} onChange={v=>{setEntranceFiles(v);setError('');}}/>
  </div>{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-footer"><span><ShieldCheck size={15}/>ข้อมูลจะบันทึกหลังยืนยันส่ง</span><button type="submit" className="btn primary"><Eye size={17}/>ตรวจสอบรายงาน</button></div>
 </form>:<div><div className="review-summary"><div><span>บริษัท</span><b>{company}</b></div><div><span>วันที่ / เวลาสำรวจ</span><b>{dateLabel(date)} · {time} น.</b></div><div><span>จุดวัด</span><b>{point}</b></div><div><span>ระดับน้ำ</span><b>{waterLevelLabel(Number(level))}</b></div><div><span>สถานการณ์</span><Badge status={status as Status}/></div><div><span>ทางเข้า–ออก</span><b>{road}</b></div><div><span>การมาทำงานของพนักงาน</span><b>{attendance}</b></div><div><span>การผลิต</span><b>{productionLabel(production)}</b></div><div><span>การจัดส่ง (ผลกระทบลูกค้า)</span><b>{transportLabel(transport)}</b></div></div>{note&&<p className="note">{note}</p>}{help&&<p className="note">ความช่วยเหลือ: {help}</p>}<div className="review-photo-grid">{previews.map((p,i)=><figure key={p}><img src={p} alt={`${photoPointLabels[i<exteriorFiles.length?'exterior':'entrance']} ภาพที่ ${i+1}`} style={{ width: '100%', height: '120px', objectFit: 'cover', borderRadius: '4px' }}/><figcaption>{photoPointLabels[i<exteriorFiles.length?'exterior':'entrance']}</figcaption></figure>)}</div><p className="review-notice">{publicMode?'รายงานนี้จะบันทึกในชุดข้อมูลจริง โดยระบุผู้ส่งเป็น ผู้ส่งรายงานทั่วไป':'รายงานนี้จะบันทึกในชุดข้อมูลจริง และระบุผู้ส่งจากบัญชีที่เข้าสู่ระบบ'}</p>{error&&<div className="form-error" role="alert">{error}{!publicMode&&<p><a href={signInHref} target="_blank" rel="noopener noreferrer" className="text-btn">ยืนยันอีเมลในแท็บใหม่ ↗</a></p>}</div>}<div className="form-footer"><button disabled={saving} className="btn secondary" onClick={()=>setReview(false)}>กลับไปแก้ไข</button><button disabled={saving} className="btn primary" onClick={()=>void submit()}>{saving?<Loader2 size={17} className="spin"/>:<CheckCircle2 size={17}/>} {saving?'กำลังบันทึก…':'ยืนยันส่งรายงาน'}</button></div></div>}
 </DialogContent></Dialog>;
}
