"use client";
import {useRef,useState} from 'react';
import {Waves,Camera,LayoutDashboard,ExternalLink,RefreshCw,Maximize,Info,Loader2} from 'lucide-react';
const SOURCE='https://cctv.dhr.go.th/';
export default function CctvView(){
 const frame=useRef<HTMLDivElement>(null);
 const [revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function fullscreen(){try{if(!document.fullscreenElement)await frame.current?.requestFullscreen();else await document.exitFullscreen();}catch{setError('อุปกรณ์นี้ไม่รองรับการขยายเต็มจอ สามารถเปิดเว็บต้นทางในแท็บใหม่ได้');}}
 return <div className="app cctv-page"><header className="masthead"><a className="brand" href="/"><div className="brand-mark"><img src="/logos/smg.png" alt="โลโก้ SMG Manufacturing Club"/></div><div><strong>SMG MANUFACTURING CLUB</strong><span>FLOOD MONITORING</span></div></a><div className="header-right"><span className="club-tag">CCTV · DONHUAROH</span><div className="avatar">SMG</div></div></header><nav className="nav-wrap cctv-navigation" aria-label="เมนูหลัก"><a href="/"><LayoutDashboard size={17}/>Dashboard สถานการณ์น้ำท่วม</a><a href="/cctv" aria-current="page"><Camera size={17}/>CCTV ดอนหัวฬ่อ</a></nav><main><div className="page-title"><div><p className="eyebrow">PUBLIC CCTV</p><h1>กล้อง CCTV ดอนหัวฬ่อ</h1><p className="subtitle">ดูสภาพถนนและพื้นที่ผ่านกล้องสาธารณะของเทศบาลเมืองดอนหัวฬ่อ</p></div><div className="title-actions"><button className="btn secondary" onClick={()=>{setLoading(true);setError('');setRevision(v=>v+1);}}><RefreshCw size={17}/>โหลดกล้องใหม่</button><a className="btn primary" href={SOURCE} target="_blank" rel="noopener noreferrer"><ExternalLink size={17}/>เปิดเว็บต้นทาง</a></div></div><div className="cctv-source"><Camera size={19}/><div><b>แหล่งภาพ: เทศบาลเมืองดอนหัวฬ่อ</b><span>เลือกตำแหน่งกล้องจากแผนที่หรือรายการภายในหน้าด้านล่าง</span></div><a href={SOURCE} target="_blank" rel="noopener noreferrer">cctv.dhr.go.th</a></div><section className="cctv-frame-panel" ref={frame}><div className="cctv-frame-bar"><span><Camera size={16}/>ระบบกล้องสาธารณะ</span><button onClick={()=>void fullscreen()} aria-label="ขยายหน้ากล้องเต็มจอ"><Maximize size={16}/>เต็มจอ</button></div>{loading&&<div className="cctv-loading" role="status"><Loader2 className="spin" size={18}/>กำลังเปิดเว็บไซต์กล้อง…</div>}<iframe key={revision} src={SOURCE} title="ระบบกล้อง CCTV เทศบาลเมืองดอนหัวฬ่อ" className="cctv-frame" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" onLoad={()=>setLoading(false)} onError={()=>{setLoading(false);setError('ยังเปิดเว็บไซต์กล้องไม่ได้ กรุณากดเปิดเว็บต้นทาง');}}/></section>{error&&<div className="error-bar" role="alert">{error}</div>}<div className="cctv-note"><Info size={18}/><p>หากภาพไม่แสดง ให้กด “เปิดเว็บต้นทาง” เพื่อดูในแท็บใหม่ ความพร้อมใช้งานและเวลาของภาพขึ้นอยู่กับระบบกล้องต้นทาง โปรดตรวจสอบวันเวลาที่แสดงในภาพก่อนใช้ประกอบการเดินทาง</p></div><footer><span><Waves size={16}/>SMG MANUFACTURING CLUB · Flood Monitoring System</span><span>ภาพจากเว็บไซต์เทศบาลเมืองดอนหัวฬ่อ</span><a href="/">กลับหน้า Dashboard</a></footer></main></div>;
}
